version: 0.0
os: linux
files:
  - source: /
    destination: /var/sites/test

permissions:
  - object: /var/sites/test
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  ApplicationStart:
    - location: scripts/test.sh
      timeout: 300
      runas: ec2-user