# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cc83cdd49655da5e7b3de35bf78e2107fd9616942c622ecb9c7a564738ddcf0464d3a2f0d6c4aa05f850bffb38d99ac6650812775c84621681f047b96472329

test:
  secret_key_base: 0eef8cfa423987d3f069b39c541c741b373194aa10726b815907afb0ad33c2ac85271bbafe77389a69edfbd8a0827067d1d73e04d89cda7e80a8ca61c1f176f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
